'system.volume.network.','system.volume.network.unmount'
'system.preferences.softwareupdate','Checked by the Admin framework when making changes to the Software Update preference pane.'
'system.print.admin'
'com.apple.builtin.confirm-access-password'
'system.install.app-store-software','Checked when user is installing software from the App Store.'
'system.install.software','Checked when user is installing new software.'
'system.volume.external.','system.volume.(external|internal|removable).(adopt|encode|mount|rename|unmount)'
'system.identity.write.self','Checked when changing authentication credentials (password or certificate) for the current user''s account.'
'system.install.app-store-software.standard-user','Checked when user is installing new software.'
'system.keychain.modify','Used by Keychain Access when editing a system keychain.'
'system.preferences.startupdisk','Checked by the Admin framework when making changes to the Startup Disk preference pane.'
'system.volume.optical.adopt','system.volume.optical.adopt'
'com.apple.ServiceManagement.blesshelper','Used by the ServiceManagement framework to add a privileged helper tool to the system launchd.'
'sys.openfile.','See authopen(1) for information on the use of this right.'
'system.privilege.taskport.debug','For use by Apple.  WARNING: administrators are advised not to modify this right.'
'system.preferences.accounts','Checked by the Admin framework when making changes to the Users & Groups preference pane.'
'com.apple.ctkbind.admin'
'system.hdd.smart','For modifying SMART settings.'
'com.apple.DiskManagement.internal.','Used by diskmanagementd to allow access to its privileged functions'
'com.apple.library-repair'
'system.preferences.sharing','Checked by the Admin framework when making changes to the Sharing preference pane.'
'system.'
'system.login.fus','Login mechanism based rule.  Not for general use, yet.'
'com.apple.Safari.allow-unsigned-app-extensions','This right is used by Safari to allow unsigned extensions in the Develop Menu.'
'com.apple.server.admin.streaming','For making administrative requests to the QuickTime Streaming Server.'
'system.volume.removable.adopt','system.volume.(external|internal|removable).(adopt|encode|mount|rename|unmount)'
'system.install.apple-software','Checked when user is installing Apple-provided software.'
'system.preferences.parental-controls','Checked when making changes to the Parental Controls preference pane.'
'com.apple.uninstalld.uninstall'
'system.preferences.nvram'
'system.print.operator'
'system.volume.removable.','system.volume.(external|internal|removable).(adopt|encode|mount|rename|unmount)'
'com.apple.builtin.generic-unlock'
'system.burn','For burning media.'
'system.device.dvd.setregion.initial','Used by the DVD player to set the region code the first time.  Note that changing the region code after it has been set requires a different right (system.device.dvd.setregion.change).'
'com.apple.OpenScripting.additions.send','Used to send restricted scripting addition commands to processes that require authorization to handle the events.'
'system.login.done'
'com.apple.opendirectoryd.linkidentity'
'com.apple.ServiceManagement.daemons.modify','Used by the ServiceManagement framework to make changes to the system launchd''s set of daemons.'
'com.apple.docset.install','Used by Xcode to restrict access to a daemon it uses to install and update documentation sets.'
'system.services.directory.configure','For making Directory Services changes.'
'system.login.screensaver','The owner or any administrator can unlock the screensaver, set rule to "authenticate-session-owner-or-admin" to enable SecurityAgent.'
'com.apple.trust-settings.user','For modifying per-user Trust Settings.'
'system.login.tty'
'system.install.apple-config-data'
'com.apple.lldb.LaunchUsingXPC'
'com.apple.Safari.parental-controls','Checked when changing parental controls for Safari.'
'system.services.networkextension.filtering','For making changes to the Content Filtering configuration using NetworkExtension.'
'system.sharepoints.','Checked when making changes to the Sharepoints.'
'system.install.software.iap'
'com.apple.XType.fontmover.remove'
'com.apple.iBooksX.ParentalControl','Checked when making changes to the Parental Controls for iBooks.'
'com.apple.icloud.passwordreset','Authenticate as the session owner to reset iCloud password'
'system.preferences.network','Checked by the Admin framework when making changes to the Network preference pane.'
'system.install.software.mdm-provided'
'system.restart','Checked if the foreground console user tries to restart the system while other users are logged in via fast-user switching.'
'system.shutdown','Checked if the foreground console user tries to shut down the system while other users are logged in via fast-user switching.'
'system.global-login-items.'
'system.preferences.energysaver'
'system.volume.external.adopt','system.volume.(external|internal|removable).(adopt|encode|mount|rename|unmount)'
'config.modify.','Wildcard right for modifying rights.  Admins are allowed to modify any (non-wildcard) rights.  Root does not require authentication.'
'system.csfde.requestpassword','Used by CoreStorage Full Disk Encryption to request the user''s password.'
'com.apple.'
'system.privilege.admin','Used by AuthorizationExecuteWithPrivileges(...). AuthorizationExecuteWithPrivileges() is used by programs requesting to run a tool as root (e.g., some installers).'
'system.install.apple-software.standard-user','Checked when user is installing new software.'
'com.apple.builtin.confirm-access'
'com.apple.pf.rule',1,1,'admin'
'config.add.','Wildcard right for adding rights.  Anyone is allowed to add any (non-wildcard) rights.'
'system.services.systemconfiguration.network','For making change to network configuration via System Configuration.'
'system.preferences.continuity','Used by Password And Continuity PrefPane to request the user''s password.'
'com.apple.trust-settings.admin','For modifying Trust Settings in the Local Admin domain.'
'system.printingmanager','For printing to locked printers.'
'com.apple.AOSNotification.FindMyMac.remove'
'system.identity.write.','For creating, changing or deleting local user accounts and groups.'
'com.apple.activitymonitor.kill','Used by Activity Monitor to authorize killing processes not owned by the user.'
'com.apple.XType.fontmover.restore'
'com.apple.appserver.privilege.user','For user access to the Application Server management tool.'
'config.remove.','Wildcard right for deleting rights.  Admins are allowed to delete any (non-wildcard) rights.  Root does not require authentication.'
'system.preferences.timemachine','Checked by the Admin framework when making changes to the Time Machine preference pane.'
'com.apple.container-repair'
'com.apple.DiskManagement.reserveKEK','Used by diskmanagementd to allow use of the reserve KEK.'
'system.localauthentication.ui','Used by LocalAuthentication to display its UI.'
'system.preferences'
'com.apple.Safari.allow-javascript-in-smart-search-field','This right is used by Safari to allow JavaScript to be used in the Smart Search Field.'
'system.preferences.datetime'
'system.disk.unlock','Do not modify.'
'com.apple.ctk.pair'
'com.apple.KerberosAgent','Used to acquire Kerberos credentials.'
'com.apple.Safari.show-passwords','This right is used by Safari to show passwords.'
'com.apple.desktopservices.scripted','For scripting-initiated privileged file operations from within the Finder.'
'com.apple.Safari.install-ephemeral-extensions','This is the right used by Safari to install an ephemeral extension without a developer certificate present.'
'com.apple.security.syntheticinput'
'system.privilege.taskport','Used by task_for_pid(...). Task_for_pid is called by programs requesting full control over another program
		for things like debugging or performance analysis. This authorization only applies if the requesting and target programs are run by the same user; it will never
		authorize access to the program of another user.  WARNING: administrators are advised not to modify this right.'
'com.apple.appserver.privilege.admin','For administrative access to the Application Server management tool.'
'com.apple.dashboard.advisory.allow'
'config.config.','Wildcard right for any change to meta-rights for db modification.  Not allowed programmatically (just edit this file).'
'com.apple.ReportPanic.fixRight'
'com.apple.desktopservices','For privileged file operations from within the Finder.'
'com.apple.Safari.show-credit-card-numbers','This right is used by Safari to show credit card numbers.'
'com.apple.builtin.generic-new-passphrase'
'system.preferences.security','Checked by the Admin framework when making changes to the Security preference pane.'
'system.preferences.version-cue','For gating modifications to Adobe Version Cue preferences.'
'system.volume.optical.','system.volume.optical.(adopt|encode|mount|rename|unmount)'
'system.preferences.location','For changing the network location from the Apple menu.'
'system.privilege.taskport.safe','For use by Apple.'
'system.preferences.accessibility','Checked when making changes to the Accessibility Preferences.'
'com.apple.security.assessment.update'
'com.apple.DiskManagement.','Used by diskmanagementd to allow access to its privileged functions'
'system.volume.','system.volume.(external|internal|removable).(adopt|encode|mount|rename|unmount)'
'com.apple.XType.fontmover.install'
'system.login.console','Login mechanism based rule.  Not for general use, yet.'
'system.preferences.printing','Checked by the Admin framework when making changes to the Printing preference pane.'
'system.services.networkextension.vpn','For making changes to the VPN configuration using NetworkExtension.'
'config.remove.system.','Wildcard right for deleting system rights.'
'system.keychain.create.loginkc','Used by the Security framework when you add an item to an unconfigured default keychain.'
'com.apple.SoftwareUpdate.scan','Checked when user is updating software.'
'com.apple.SoftwareUpdate.modify-settings','Checked by the Admin framework when making changes to the Software Update preference pane.'
'system.preferences.security.remotepair','Used by Bezel Services to gate IR remote pairing.'
'system.identity.write.credential','Checked when changing authentication credentials (password or certificate) for a local user account.'
'com.apple.builtin.sc-kc-new-passphrase'
'com.apple.AOSNotification.FindMyMac.modify'
'com.apple.Safari.allow-apple-events-to-run-javascript','This right is used by Safari to allow Apple Events to run JavaScript on web pages.'
'com.apple.CoreRAID.admin','com.apple.CoreRAIDServer','Used by CoreRAID to allow access to administration functions of RAID devices'
'com.apple.wireless-diagnostics','com.apple.wdhelper','Used by the WirelessDiagnosticsSupport framework to restrict XPC services provided by the wdhelper daemon'
'com.apple.wifi','com.apple.airport.airportd','For restricting WiFi control'
'com.apple.familycontrols.override','com.apple.parentalcontrolsd','This right is checked when overriding parental controls from a user account'
'com.apple.familycontrols.loginwindow.override','com.apple.parentalcontrolsd','This right is checked when overriding a parental control restriction'
'com.apple.wifivelocity','com.apple.$(PRODUCT_BUNDLE_IDENTIFIER)','Used by the WiFiVelocity framework to restrict XPC services'
